language: python





python:
  # - "2.7"
  # - "3.3"
  # - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch

# cache pip files between builds
cache: pip

os:
  - linux
  # - osx

# command to install dependencies
install:
  - pip install -r requirements.txt

  - pip install coveralls

  - cd test && coverage run -m pytest

script:
  - pytest

after_success: coveralls
