# -*- coding: utf-8 -*-

# this file contains constant data that the bot gives back to users

# sources of this data: http://www.18thjudicialcircuitpublicdefender.com/client-information/


FIRST_APPEARANCE = "You will appear before a judge within 24 hours of your arrest if you cannot post the bail in the bail schedule amount set by the chief judge of the 18th Judicial Circuit. Before the Public Defender may represent you, the court must make an inquiry into your finances and appoint the Public Defender’s Office to serve as your legal counsel. The judge will ask if you want to have a lawyer present and whether you need a court-appointed lawyer because you are unable to afford to hire one. The judge will advise you of your charge or charges. The judge will decide if the police had a legally sufficient reason to arrest you, known as probable cause."

BAIL = "Bail is intended to guarantee you will appear for your court appearances. You do not have a right to bail if you are charged with a crime that carries a penalty of either life imprisonment or death, which may include murder, sexual battery, kidnapping, burglary and robbery. To lower the amount of bail or to have the court set bail, the judge must be convinced you will be in court when notified. You may be asked several questions such as whether you have a family living in the area, whether you are working, whether you have been bailed out before and appeared in court on time, where you live and your criminal record. If the court finds you are not charged with a serious crime, that you will appear when required in court or that you have a responsible person in the community who will guarantee your appearance in court, the judge may decide to release you without bail. A motion may be filed by your assistant public defender for reduction of bail if the bail in your case seems high in view of the charge, the evidence against you, or your personal background."

INTAKE = """The first person you will see from the Public Defender’s Office may be either an assistant public defender, a witness interviewer, an investigator or a legal intern for what is called intake. Even though this interviewer may not be an attorney, the information you give is confidential and will be given to your lawyer. You will be asked a number of questions. It is important to cooperate fully and answer all questions truthfully.


If you are not in jail, you must contact the Public Defender’s Office as soon as possible to make an appointment to see your lawyer. Please do not wait until the day before your trial or your court date."""

JAIL_VISITS = "The Public Defender’s staff visits the jails to meet with our clients. We will meet with you when necessary. If telephones are available at the jail, a call will often solve your problem. Do not discuss the facts of your case on the telephone or in the hearing of other people. You should request a jail visit when it is important that you and your lawyer meet in person. Only the people in charge of the jail can decide if your friends and relatives can visit you. Questions about food, clothing and medicine should also be directed to the people in charge of the jail."


FILING_FORMAL_CHARGES = "If you are in jail, the prosecutor has 40 days to file formal charges against you before you must be released without having to post bail. If formal charges are not filed within 33 days, the Public Defender will schedule you to be brought before the judge at the jail to decide whether the state should be given an additional 7 days in which to file the formal charging document called the information."

ARRAIGNMENT = "After your first appearance, an arraignment will be scheduled in your case. At arraignment, your charges may be read, a lawyer from the Public Defender’s Office enters your plea and, if the plea is “not guilty,” requests either a trial by jury or judge. The trial date will be set at that time.  Often the public defender will waive the formal reading of the charges at arraignment."

INVESTIGATING_YOUR_CASE = """Anything you tell a public defender investigator or intern, just as anything you tell your lawyer, is confidential. Do not discuss your case with anyone else including your family, friends, cellmates, news reporters, probation officer or police officers unless your lawyer says you can, since all of these people can be made to testify against you.  Do not send the judge a letter which discusses your case in any way as the judge will immediately give the letter to the state attorney for use against you. Your lawyer and investigator must know the truth, even if you are guilty, think you are guilty, or the truth makes you look guilty. If the truth is known, your lawyers will not be caught off guard and will be able to better represent you."

You can help in the investigation of your case by giving the names and addresses of witnesses. If you are out of jail, you can help your case by finding witnesses and notifying your lawyer by sending a letter, calling or coming to the office with the names and addresses. If you are in jail, try to have your family and friends find witnesses. Witnesses may be anyone who can testify to any circumstances which may show you are not guilty or which may tend to show that the crime was not as serious as the prosecutor claims.

Your investigator may interview the witnesses against you and try to locate defense witnesses. Accurate names and addresses are helpful. You should not, however, contact witnesses for the prosecution or send other people to talk to them for you. If you do, you may be charged with the crime of witness tampering."""


PREPARING_YOUR_CASE = """We cannot represent you on your case until we are appointed by a judge. Once appointed, we will interview you and get a copy of the charges against you. This all takes time. Each case is different. Complicated cases naturally take longer than other cases. Remember, an extra month or two in jail may save you from years in prison. Your lawyer must be thoroughly prepared before he can go into court for you. If you do not understand why your case is taking so long to prepare, talk to your lawyer and he will explain it to you."

If you are unhappy with the way your case is being handled, talk to your lawyer. If you are still not satisfied, state your complaint in writing and mail it to the Public Defender. You are not entitled to the lawyer of your choice unless you can hire a private lawyer or qualify to represent yourself. When writing to your lawyer with a complaint or question, it is wise to mark the envelope: “Confidential, Attorney/Client Communication. Do Not Censor.

Your lawyer may file discovery motions to get witness lists, police reports, witnesses’ statements, reports of experts and all other important facts in your case. Discovery depositions and other statements given under oath may be taken from witnesses. Your lawyer may also talk with the prosecutor to get some idea of how the prosecutor feels about your case. The prosecutor may decide to dismiss all charges or to “plea bargain” — that is agree to a lighter sentence or drop some of several charges against you, in exchange for a plea of guilty or nolo contendere which means no contest. All communication between you and your lawyer is confidential. Without your permission, confidential information cannot be revealed to the prosecutor or anyone. Once the preparation of your case is complete, your lawyer will inform you of all the facts and explain available defenses as well as the chances of success. Your lawyer will also explain possible sentences if you plead guilty or are found guilty at trial. A criminal defense attorney is bound by the rules of ethics to notify you of any plea bargain offered by the state attorney. It is important that you not take this to mean that the attorney is trying to get you to plead guilty or no contest."""


MOTIONS = "After investigating your case, your lawyer may file motions and ask for a court hearing. You should not file your own motions. Because you are not a lawyer, you may put something in a motion that could hurt your case. If you have a matter that you want the court to know about, ask your lawyer to handle it for you."

PRE_TRIAL = "The Pre-Trial Intervention Program offers an alternative to formal prosecution. The program is very selective primarily for first offenders or people with no significant prior record. It cannot accept applicants without the approval of the victim, arresting officer, prosecutor and judge. If you successfully complete this program, your charges will be dismissed."

COURT_APPEARANCES = """You must appear in court for all your court hearings unless told otherwise by your lawyer.

If you change your address or phone number while waiting to come to trial, notify your lawyer immediately so that you can be notified when you must be in court. It is best to arrive before the time scheduled in order to discuss your case with your lawyer. If you cannot appear in court on time, notify your lawyer immediately. If you do not and are late, the judge may issue a warrant for your arrest and your right to a speedy trial may be lost.  You should always dress well for court if at all able.  Well-dressed defendants demonstrate respect for the court and the justice system.  A well-dressed appearance, clean-shaven for men, can help to make a favorable impression upon the court.  You should dress to cover tatoos and remove all visible body-piercings except earrings."""

PLEAS = """Under the law you are presumed innocent until proven guilty. You can only plead one of three ways: (1) Not Guilty, (2) Guilty, or (3) Nolo Contendere, which is Latin for no contest. A not guilty plea is entered when you are innocent, when you are not certain of which plea to enter, when there is not enough evidence against you to prove guilt or when you want to demand a public trial. If you plead guilty or nolo contendere, either to the charges against you or to some lesser charge, you must convince the judge you know what you are doing and that no one is forcing you to do so.

If you plead guilty, you must admit you committed the crime. After talking with your lawyer, the decision to plead guilty is strictly up to you. By pleading guilty you give up your right to trial by a jury or judge, which includes your right to face and question witnesses against you, and your right to remain silent.  You cannot plead guilty or no contest and then claim in an appeal of your case that you are not guilty.

A nolo contendere plea allows the judge to find you guilty without you admitting your guilt. A plea of nolo contendere, if accepted by the judge, has the same effect as a plea of guilty. It means you do not admit your guilt but do not want a trial because you believe a trial is not in your best interest.

A negotiated plea is an agreement between your lawyer, acting with your permission, and the prosecutor for reduction of charges, dismissal of some charges and/or an appropriate sentence. Such a negotiated plea can only be entered with your approval. The judge is not required to accept any negotiated plea agreement."""

CHANGING_A_PLEA = "If, after talking with your lawyer, you decide to change your plea of not guilty to either guilty or nolo contendere, your lawyer will explain to the court that you want to change your plea. Before accepting your plea, the judge will ask you certain questions to make sure you understand all your rights that you are waiving by pleading guilty or no contest, and that no one has pressured you into changing your plea. You alone must decide to change your plea and the court wants to make sure of that."


TRIAL = """If you plead not guilty, you will have a trial unless the charges are dismissed or you change your plea before trial. In a jury trial, a judge will preside and six  citizens from the community (12 in first degree murder cases in which the death penalty is sought) will determine if the state has produced evidence which convinces the jury beyond a reasonable doubt whether you are guilty. A non-jury trial is where the judge decides the case instead of a jury. You and your lawyer must decide whether you want a jury trial, you must decide whether or not you will testify. You are not required to testify, but, you can give up that right and testify if you wish. Your lawyer will give you his advice about this and help you decide.

A jury is used for most trials. Your lawyer will question the prospective jurors and, with your assistance, try to select the best ones to sit on your case. After both sides question the jury and the jurors are agreed upon, the case begins. Next, each side can make an opening statement telling the jury what they believe the evidence will prove or not prove. The prosecutor then presents witnesses and evidence. Your lawyer can cross-examine these witnesses. If the State’s witnesses do not appear in court for your trial, the judge may  postpone it at the request of the prosecutor. This decision is up to the judge.

After the prosecution witnesses testify, your lawyer has a chance to ask the judge to enter a directed verdict of not guilty (judgment of acquittal) in your case if the prosecutor did not present enough evidence to show that you did anything wrong. If this motion is denied, then your lawyer may present defense witnesses and evidence which may be rebutted by the prosecutor. The decision as to how to best defend your case is complex and should be discussed  with your lawyer. After all evidence is presented, each side makes their final argument to the jury. The judge then instructs the jury on the elements of the crime or crimes charged and the rules to be applied during their deliberation. The jury then goes into a jury room to deliberate the case until they reach a unanimous verdict. If they cannot reach a unanimous verdict, a mistrial occurs and your case is reset for trial at a later date.

Even though the judge sets a trial date, you may or may not be tried on that date. Since there are so many people awaiting trial, the judges set a large number of cases for the same day as your case. Your case may stay on the trial docket from one day to the next until your turn comes, unless your lawyer or the prosecutor needs extra time to prepare for your case. You may be required to appear at the courthouse several times and stay there all day without having your case come up. Some cases may take priority over your case, because the defendant is either in jail or for some other reason"""



SENTENCING = "If you are to be sentenced, you will have a chance to talk to the judge at the sentencing hearing. You should discuss with your lawyer whether to talk to the judge and, if so, what to say. The judge will also give your lawyer and any other interested persons a chance to speak on your behalf. Let your lawyers know in advance the names and addresses of people you want to speak at your sentencing. You should not compare the sentence in your case with those in other cases because each case is different."


ALTERNATIVE_SENTENCING  = "If you feel your arrest was caused by an alcohol, drug or mental problem, please tell your lawyer. You may be eligible for programs to treat these conditions. These programs may be an alternative to jail or prison."


PROBATION = "Probation is a privilege–not a right. If you are a first-time offender, this does not mean you will automatically receive probation. If placed on probation, the usual conditions include: (1) reporting regularly to your probation officer, (2) notifying and receiving permission from your probation officer before changing your address, changing your job or leaving the county, and (3) leading a law-abiding life and not committing any other crimes. If you violate any of these probation conditions, or any special conditions required by the judge, the judge may sentence you to prison or jail. If the violation of probation is a crime committed by you while on probation, the judge can revoke your probation without waiting until you are convicted of the new charge. A probation violation hearing will be held by a judge without a jury."


PAYMENT = "If you are found guilty, the judge may require you to pay attorney fees, restitution or other charges."



APPEAL = "If you are convicted and want to appeal your case, you must do so within 30 days after sentencing. You have no right to an appeal from a plea of guilty or nolo contendere when a legal sentence was imposed. An appeal will only help you if the judge did not follow the law, or if you were prevented from properly exercising all your rights. You or your lawyer argue in written briefs to the appellate court exactly how the judge didn’t follow the law or what rights you were denied before it will reverse a conviction. If your case is appealed in some cases the law allows the judge to release you on bail until a final decision is reached if the judge believes you will reappear in court. If you wish to appeal your case, you should discuss this matter with your lawyer as soon as possible."




JUVENILE_COURT = """If you are a juvenile (under 18 years of age) and your case remains in juvenile court, you may be held at a facility for juveniles rather than a jail depending on your criminal record and the seriousness of the crime for which you were arrested. Your first court hearing is called a detention hearing, not a first appearance. At that hearing, the judge will decide whether you should be released from custody and may appoint a lawyer from the Office of the Public Defender to represent you. If the Public Defender is appointed and you are released from custody, you must contact the Public Defender’s office immediately for an appointment to see your lawyer.


Even if you are under age 18, under certain circumstances, you may be tried as an adult. Your prior record and the seriousness of the charge may be considered. If you are to be tried as a juvenile you may be released from custody through a program called non-secure detention. Your lawyer may ask for you to be interviewed for non-secure detention, and will ask the judge for your release.  Only the judge can place you in the program. Non-secure detention allows you to live at home while waiting for trial. A counselor will contact you periodically. You may be returned to custody if you do not follow rules set by your counselor. After the detention hearing there will be an arraignment where you will be asked to enter your plea. The various pleas available to you and the procedures to be followed in handling your case are similar to those for adults except, you do not have a right to a jury trial. Your case will be heard and decided by a judge assigned to the juvenile court. Your trial will be called an adjudicatory hearing. If you have been found not guilty by the judge or if your case has been dismissed, you will be released and there will be no further proceedings in your case. If you are found guilty at the adjudicatory hearing, you will have a dispositional hearing where the judge decides what will happen to you.


In order to determine the disposition of your case, the judge will look at the facts and your personal background including your prior record, if any. Your counselor will provide a report on your background. The judge can commit you to the Department of Juvenile Justice, place you on probation or order you to participate in a community control program. You should not compare the disposition of your case with other cases, because each case is different. If the judge orders you to participate in community control, you may be required to repay the victim for any damages, or provide some kind of service working for your community. If you do not complete your responsibilities under community control, you may be brought back to court. Your lawyer will represent you at this hearing and must explain your problem. You may be committed to the Department of Juvenile Justice if the judge finds that you have not done what he told you to do.  A commitment to the Department of Juvenile Justice usually means you’ll be taken out of your home. It also subjects you to the possibility of being sent to a state training school."""


YOUR_RIGHT_TO_COUNSEL = "The Founding Fathers of our country believed that every citizen has a fundamental right to a fair trial and access to counsel is an essential component for fairness. The United States Constitution, through the Sixth Amendment of the Bill of Rights, guarantees each citizen haled into criminal court and facing loss of liberty the right to counsel. This right extends to the states through the Due Process Clause of the Fourteenth Amendment to the Constitution. Nevertheless, for many years individuals in state court who were unable to pay an attorney went to trail and represented themselves. In 1963, Clarence Earl Gideon, a man with an eighth grade education, sought relief from the United States Supreme Court from his conviction in a Florida state court that had denied his requests for a lawyer. Representing himself, Mr. Gideon was found guilty of breaking and entering and was sentenced to five years in prison. He petitioned the Supreme court on whether he had a right to representation at trial. The Supreme Court considered his case and recognized “fair trials before impartial tribunals in which every defendant stands equal before the law cannot be realized if the poor man charged with crime has to face his accusers without a lawyer to assist him. Gideon v. Wainright. 372 US 335,344 (1963) Since then, individuals facing a loss of liberty in state court who cannot afford a lawyer may have one appointed to represent them. Representation by the Public Defender is not free, however. There is a $50.00 application fee payable to the Clerk of the Court within seven days of appointment and there may be additional fees depending on the outcome of the case."


YOUR_APPOINTMENT = "The court must appoint the Public Defender for you. Request the Public Defender at your first appearance before a judge and complete the affidavit of indigency to apply and to show you cannot afford a lawyer. The judge will ask you some questions about your resources and will make the determination. There is a $50.00 Public Defender Application Fee payable to the Clerk of the Court within seven days of appointment."


HELPFUL_FACTS = """
Case Dismissed or Acquitted: Even if your case is dismissed or you are acquitted at trial, you still have a criminal record. Once you are charged with a crime, a criminal record exists on you.


Expunging Your Record: By statute the Public Defender represents persons in an active prosecution for an alleged crime or facing loss of liberty.  The Public Defender is prohibited from representing persons seeking expunction or sealing of their criminal record.  You may petition the court for expunction of a record for which your charge was dismissed or you were acquitted. You must obtain a certificate of eligibility for expunction from the Florida Department of Law Enforcement prior to petitioning for expunction. If your criminal history shows a violation of certain statutes, you may be ineligible. The application and information are available at the Florida Department of Law Enforcement Website:


Sealing your record: By statute the Public Defender represents persons in an active prosecution for an alleged crime or facing loss of liberty.  The Public Defender is prohibited from representing persons seeking expunction or sealing of their criminal record. You may petition the court to seal a record for which your charge was dismissed or you were acquitted. You must obtain a certificate of eligibility from the Florida Department of Law Enforcement prior to petitioning for the court to seal your record. If your criminal history record shows a violation of certain statutes, you may be ineligible. The application and information are available at the Florida Department of law Enforcement Website:


Restoration of civil rights following incarceration: In Florida, a convicted felon cannot vote, serve on a jury, or hold public office until civil rights have been restored. Completion of a sentence does not restore those rights, you must apply to the Office of Executive Clemency for restoration. This is a lengthy process. Eligibility requires completion of the sentence, payment of all fees, fines and restitution and a waiting period of five to 10 years after the completion of your sentence."""


REENTRY = " Take a look at this guide: http://www.18thjudicialcircuitpublicdefender.com/wp-content/uploads/2013/01/2-September-2014-Jail-Reentry-Manual-Working.pdf"



intent_message_key_mappings = {
        # intro mappings
         'court_basics': FIRST_APPEARANCE,
         'bail':         BAIL,
         'jail_visits':  JAIL_VISITS,
         'trial':        TRIAL,
         'appeal':       APPEAL,
        }
